# Generated by Django 3.2.7 on 2021-09-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.IntegerField(default=1),
        ),
    ]
